---
  model: ???
  model_name: ''
  method: ???
  num_runs: 5
  num_iters: 1000
  Ks_lrs: {10: [0.001, 0.03, 0.1], 30: [0.001, 0.03, 0.1]}
  reparam: True
  save_moments: False
  predll:
    do_predll: True
    N_predll: 100
  dataset_seed: 0
  write_job_status: True
  split:
    plate: null
    size: null
  results_subfolder: ''
  non_mp: False