---
  model: ???
  method: ???
  num_runs: 5
  num_iters: 1000
  Ks: [3,10,30] #,100]
  reparam: True
  predll:
    do_predll: True
    N_predll: 100
  lrs: [0.1, 0.01, 0.001, 0.0001]
  dataset_seed: 0
  write_job_status: True
  split:
    plate: null
    size: null