---
  model: ???
  method: ???
  num_runs: 5
  num_iters: 1000
  Ks: [3,10,30] #,100]
  reparam: True
  predll:
    do_predll: True
    N_predll: 100
  lrs: [0.3,0.1,0.03,0.01]
  dataset_seed: 0
  write_job_status: True
  split:
    plate: null
    size: null
  results_subfolder: ''
  non_mp: False